backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\Group;
use common\models\Student;
use common\models\University;
use Yii;
use yii\data\Pagination;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => [
                            'newuniversity',
                            'university',
                            'deleteuniversity',
                            'newgroup',
                            'group',
                            'deletegroup',
                            'newstudent',
                            'student',
                            'deletestudent',
                        ],
                        'allow' => true,
                        'matchCallback' => function() {
                            if(isset(Yii::$app->user->identity->role)) {
                                if(Yii::$app->user->identity->role !== "admin") {
                                    return false;
                                } else return true;
                            } else return false;
                        }
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->accessControl()) {
            $model->login();
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    //универы
    public function actionUniversity()
    {
        $query = University::find();
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 3]);
        $uni = $query->offset($pages->offset)->limit($pages->limit)->orderBy(['id' => SORT_DESC])->all();

        return $this->render('university', compact(['pages', 'uni']));
    }

    public function actionNewuniversity()
    {
        $model = new University();
        if($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            return $this->redirect(['site/university']);
        }

        return $this->render('newuniversity', compact(['model']));
    }

    public function actionDeleteuniversity($id = null)
    {
        University::deleteAll(['id' => $id]);
        return $this->redirect(['site/university']);
    }

    //группы
    public function actionNewgroup()
    {
        $model = new Group();
        $uni = University::generateTitleList();
        if($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            return $this->redirect(['site/group']);
        }

        return $this->render('newgroup', compact(['model', 'uni']));
    }

    public function actionGroup()
    {
        $query = Group::find();
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 3]);
        $groups = $query->offset($pages->offset)->limit($pages->limit)->orderBy(['id' => SORT_DESC])->all();
        foreach($groups as $g) {
            $u = University::findOne(['id' => $g->university_id]);
            $g->university_id = $u->title;
        }
        return $this->render('group', compact(['pages', 'groups']));
    }

    public function actionDeletegroup($id = null)
    {
        Group::deleteAll(['id' => $id]);
        return $this->redirect(['site/group']);
    }

    //студенты
    public function actionNewstudent()
    {
        $model = new Student();
        $uni = University::generateTitleList();
        $gro = Group::generateTitleList();
        if($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->save();
            return $this->redirect(['site/student']);
        }

        return $this->render('newstudent', compact(['model', 'uni', 'gro']));
    }

    public function actionStudent()
    {
        $query = Student::find();
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 3]);
        $students = $query->offset($pages->offset)->limit($pages->limit)->orderBy(['id' => SORT_DESC])->all();
        foreach($students as $s) {
            $u = University::findOne(['id' => $s->university_id]);
            $g = Group::findOne(['id' => $s->group_id]);
            $s->university_id = $u->title;
            $s->group_id = $g->title;
        }
        return $this->render('student', compact(['pages', 'students']));
    }

    public function actionDeletestudent($id = null)
    {
        Student::deleteAll(['id' => $id]);
        return $this->redirect(['site/student']);
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Group;
use common\models\University;
use Yii;
use yii\base\InvalidParamException;
use yii\data\Pagination;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use common\models\Student;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex($sort_gro = null, $sort_uni = null)
    {
        if($sort_gro !== null) {
            $id = Group::findOne(['title' => $sort_gro]);
            $query = Student::find()->where(['group_id' => $id->id]);
        }
        if($sort_uni !== null) {
            $id = University::findOne(['title' => $sort_uni]);
            $query = Student::find()->where(['university_id' => $id->id]);
        }
        if($sort_uni === null && $sort_gro === null) {
            $query = Student::find();
        }
        $pages = new Pagination(['totalCount' => $query->count(), 'pageSize' => 3]);
        $students = $query->offset($pages->offset)->limit($pages->limit)->orderBy(['id' => SORT_DESC])->all();
        foreach($students as $s) {
            $u = University::findOne(['id' => $s->university_id]);
            $g = Group::findOne(['id' => $s->group_id]);
            $s->university_id = $u->title;
            $s->group_id = $g->title;
        }
        return $this->render('index', compact(['students', 'pages']));
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending your message.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/group.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii\widgets\LinkPager;

$this->title = 'Группы';

?>

<?= Html::a('Добавить', ['site/newgroup'], ['class' => 'btn btn-primary']) ?>
<?php Pjax::begin() ?>
    <table class="table">
        <tr>
            <th>Название</th>
            <th>Специальность</th>
            <th>Курс</th>
            <th>Университет</th>
            <th>Опции</th>
        </tr>
        <?php foreach($groups as $g): ?>
            <tr>
                <td><?= $g->title ?></td>
                <td><?= $g->profile ?></td>
                <td><?= $g->year ?></td>
                <td><?= $g->university_id ?></a></td>
                <td><?= Html::a('', Url::to(['site/deletegroup', 'id' => $g->id]), ['class' => 'glyphicon glyphicon-remove']) ?></td>
            </tr>
        <?php endforeach ?>
    </table>
<?= LinkPager::widget(['pagination' => $pages]) ?>
<?php Pjax::end() ?>

backend/views/site/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/doc/">Yii Documentation &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/forum/">Yii Forum &raquo;</a></p>
            </div>
            <div class="col-lg-4">
                <h2>Heading</h2>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.</p>

                <p><a class="btn btn-default" href="http://www.yiiframework.com/extensions/">Yii Extensions &raquo;</a></p>
            </div>
        </div>

    </div>
</div>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/site/newgroup.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Группы - Добавить';

?>

<div class="col-md-4">
    <?php $form =  ActiveForm::begin() ?>
    <?= $form->field($model, 'title')->textInput() ?>
    <?= $form->field($model, 'profile')->textInput() ?>
    <?= $form->field($model, 'year')->input('number') ?>
    <?= $form->field($model, 'university_id')->dropDownList($uni) ?>
    <?= Html::submitButton("Добавить", ['class' => 'btn btn-success']) ?>
    <?php ActiveForm::end() ?>
</div>

backend/views/site/newstudent.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Студенты - Добавить';

?>

<div class="col-md-4">
    <?php $form =  ActiveForm::begin() ?>
    <?= $form->field($model, 'name')->textInput() ?>
    <?= $form->field($model, 'study_date')->input('date') ?>
    <?= $form->field($model, 'group_id')->dropDownList($gro) ?>
    <?= $form->field($model, 'university_id')->dropDownList($uni) ?>
    <?= Html::submitButton("Добавить", ['class' => 'btn btn-success']) ?>
    <?php ActiveForm::end() ?>
</div>

backend/views/site/newuniversity.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Университеты - Добавить';

?>

<div class="col-md-4">
    <?php $form =  ActiveForm::begin() ?>
    <?= $form->field($model, 'title')->textInput() ?>
    <?= $form->field($model, 'adress')->textInput() ?>
    <?= $form->field($model, 'rector')->textInput() ?>
    <?= $form->field($model, 'site')->textInput() ?>
    <?= $form->field($model, 'ur_adress')->textarea() ?>
    <?= Html::submitButton("Добавить", ['class' => 'btn btn-success']) ?>
    <?php ActiveForm::end() ?>
</div>

backend/views/site/student.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii\widgets\LinkPager;

$this->title = 'Студенты';

?>

<?= Html::a('Добавить', ['site/newstudent'], ['class' => 'btn btn-primary']) ?>
<?php Pjax::begin() ?>
    <table class="table">
        <tr>
            <th>ФИО</th>
            <th>Дата поступления</th>
            <th>Группа</th>
            <th>Университет</th>
            <th>Опции</th>
        </tr>
        <?php foreach($students as $s): ?>
            <tr>
                <td><?= $s->name ?></td>
                <td><?= $s->study_date ?></td>
                <td><?= $s->group_id ?></td>
                <td><?= $s->university_id ?></a></td>
                <td><?= Html::a('', Url::to(['site/deletestudent', 'id' => $s->id]), ['class' => 'glyphicon glyphicon-remove']) ?></td>
            </tr>
        <?php endforeach ?>
    </table>
<?= LinkPager::widget(['pagination' => $pages]) ?>
<?php Pjax::end() ?>

backend/views/site/university.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Pjax;
use yii\widgets\LinkPager;

$this->title = 'Университеты';

?>

<?= Html::a('Добавить', ['site/newuniversity'], ['class' => 'btn btn-primary']) ?>
<?php Pjax::begin() ?>
<table class="table">
    <tr>
        <th>Название</th>
        <th>Адрес</th>
        <th>Ректор</th>
        <th>Веб-сайт</th>
        <th>Юр. адрес</th>
        <th>Опции</th>
    </tr>
    <?php foreach($uni as $u): ?>
        <tr>
            <td><?= $u->title ?></td>
            <td><?= $u->adress ?></td>
            <td><?= $u->rector ?></td>
            <td><a href="<?= $u->site ?>"><?= $u->site ?></a></td>
            <td><?= $u->ur_adress ?></td>
            <td><?= Html::a('', Url::to(['site/deleteuniversity', 'id' => $u->id]), ['class' => 'glyphicon glyphicon-remove']) ?></td>
        </tr>
    <?php endforeach ?>
</table>
<?= LinkPager::widget(['pagination' => $pages]) ?>
<?php Pjax::end() ?>